# .bashrc
# linux uses .bashrc for non-login shell
# osx uses .bashrc for login shell

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# alias
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# env variables                                                                                                                                                                                                                              
export CLICOLOR=1  # osx color files/folders                                                                        
export ACKRC=".ackrc"  # ack configuration

source ~/.git-completion.bash
source ~/.rvm/scripts/rvm
source "$rvm_path/contrib/ps1_functions"

PATH=$PATH:$HOME/bin 
#PATH=$PATH:$(xcode-select -print-path)
export PATH


#PS1="\$(~/.rvm/bin/rvm-prompt) $PS1"
ps1_set $
